Added isna example with Series.map
Bodo-inc/Bodo-tutorial pull request #16
Opened 2021-02-17 01:20 UTC by njriasan

Adds an example of checking for isna to prevent garbage values.

2021-02-17 14:15 UTC, ritwika314 approved these changes
looks good to me , thanks!

2021-02-17 15:58 UTC, ehsantn requested changes
See comments.

2021-02-17 15:58 UTC, ehsantn commented on bodo_tutorial.ipynb
> +    "When an operation iterates over the values in a Series or Array, type stablity requires special handling for NAs using `pd.isna()`. For example, `Series.map()` applies an operation to each eleme
I think this section is different than the previous one, so it needs a new title. Maybe something like: "Checking NA Values".

Also, I think it can be misleading to show the wrong example where garbage values propagating. It may be understood as the correct way.

2021-02-17 15:58 UTC, ehsantn commented on bodo_tutorial.ipynb
> +    "                np.array([False, True, True, False, False]),\n",
This could be `pd.array([1, None, None, 3,  10], dtype="Int8")`.

2021-02-17 19:41 UTC, njriasan commented on bodo_tutorial.ipynb
> +    "When an operation iterates over the values in a Series or Array, type stablity requires special handling for NAs using `pd.isna()`. For example, `Series.map()` applies an operation to each eleme
Ok I'll make these changes. Thanks!

2021-02-17 19:46 UTC, njriasan commented on bodo_tutorial.ipynb
> +    "                np.array([False, True, True, False, False]),\n",
Done.

2021-02-17 19:47 UTC, njriasan commented on bodo_tutorial.ipynb
> +    "When an operation iterates over the values in a Series or Array, type stablity requires special handling for NAs using `pd.isna()`. For example, `Series.map()` applies an operation to each eleme
Done.

2021-02-18 04:17 UTC, ehsantn approved these changes
Looks good. Thanks.

2021-02-18 17:28 UTC, merged